### ISSUE TITLE
Rename components with prefix

### ISSUE THREAD

**Issue by Eoksni** [emotz/enotgame#17]
create -> eg-create
ready -> eg-ready

**Comment by Eoksni** [comment]
@ITarako Хм, как-то не очень хорошо, что ты закрываешь issues за просто так, без коммитов и пояснений. Они тебе глаза мозолят после того как ты их в своей ветке закрыл? Можно тогда гитхаб проекты использовать, там можно больше статусов добавить, чем простое "open/closed", по типу "open/inprogress/testing/done in branch/closed".

**Comment by ITarako** [comment]
[added "vue-loader" & refactoring vue components  …
closed 17](https://github.com/emotz/enotgame/pull/16/commits/f023b8084a406a3344d18e5552d9de077d09bb07)
